language: python
python: 3.7

install:
  - pip install poetry
  - poetry install

script:
  - poetry run mypy perseus
  - poetry build

deploy:
  - provider: script
    script: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD --build
    on:
      tags: true
